apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 4
  strategy:
    canary:
      maxSurge: 100%
      minPodsPerReplicaSet: 2
      maxUnavailable: 5%
      steps:
      - setWeight: 20
      - pause: {duration: 20}
      - setWeight: 80
      - pause: {duration: 3}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    other_stuff: something
    spec:
      restartPolicy: Always
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

